# for local development
spring:
  datasource:
    url: jdbc:postgresql://localhost:${PG_PORT:5433}/${PG_DB:todo_db}
    username: ${PG_USER:todo_user}
    password: ${PG_PASSWORD:todo_pass}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  profiles:
    active: dev

# Dev CORS, allow Vite on 5173
app:
  cors:
    origins: "http://localhost:5173"

gcs:
  bucket-name: "todo-app-profile-images-dev"
